/**
 **************************************************************************************
 *** CommentDAOException.java                                                       ***
 *** Generator: net.anotheria.asg.generator.model.db.PersistenceServiceDAOGenerator ***
 *** generated by AnoSiteGenerator (ASG), Version: 1.3.3                            ***
 *** Copyright (C) 2005 - 2010 Anotheria.net, www.anotheria.net                     ***
 *** All Rights Reserved.                                                           ***
 **************************************************************************************
 *** Don't edit this code, if you aren't sure                                       ***
 *** that you do exactly know what you are doing!                                   ***
 *** It's better to invest time in the generator, as into the generated code.       ***
 **************************************************************************************
 */

package net.anotheria.moskitodemo.annotation;

import net.anotheria.db.dao.DAOException;

public class CommentDAOException extends DAOException{

	public CommentDAOException(String message){
		super(message);
	}

	public CommentDAOException(){
		super();
	}
}
