/**
 ********************************************************************************
 *** CommentFactory.java                                                      ***
 *** generated by AnoSiteGenerator (ASG), Version: 1.3.3                      ***
 *** Copyright (C) 2005 - 2010 Anotheria.net, www.anotheria.net               ***
 *** All Rights Reserved.                                                     ***
 ********************************************************************************
 *** Don't edit this code, if you aren't sure                                 ***
 *** that you do exactly know what you are doing!                             ***
 *** It's better to invest time in the generator, as into the generated code. ***
 ********************************************************************************
 */

package net.java.dev.moskitodemo.annotation.data;


public class CommentFactory{

	public static Comment createComment(Comment template){
		return new CommentVO((CommentVO)template);
	}

	public static Comment createComment(){
		return new CommentVO("");
	}

	static Comment createComment(CommentBuilder builder){
		return new CommentVO(builder);
	}

	public static Comment createCommentForImport(String anId){
		return new CommentVO(anId);
	}

	/**
	 * For internal use only!
	 */
	public static Comment createComment(String anId){
		return new CommentVO(anId);
	}
}
