/**
 ********************************************************************************
 *** CommentBuilder.java                                                      ***
 *** generated by AnoSiteGenerator (ASG), Version: 1.3.3                      ***
 *** Copyright (C) 2005 - 2010 Anotheria.net, www.anotheria.net               ***
 *** All Rights Reserved.                                                     ***
 ********************************************************************************
 *** Don't edit this code, if you aren't sure                                 ***
 *** that you do exactly know what you are doing!                             ***
 *** It's better to invest time in the generator, as into the generated code. ***
 ********************************************************************************
 */

package net.java.dev.moskitodemo.sqltrace.persistence.data;

public class CommentBuilder {

	protected String firstName;
	protected String lastName;
	protected String email;
	protected String text;
	protected long timestamp;
	protected boolean wishesUpdates;

	/**
	 * Sets the value of the firstName attribute.
	 */
	public CommentBuilder firstName(String aValue){
		firstName = aValue;
		return this;
	}

	/**
	 * Sets the value of the lastName attribute.
	 */
	public CommentBuilder lastName(String aValue){
		lastName = aValue;
		return this;
	}

	/**
	 * Sets the value of the email attribute.
	 */
	public CommentBuilder email(String aValue){
		email = aValue;
		return this;
	}

	/**
	 * Sets the value of the text attribute.
	 */
	public CommentBuilder text(String aValue){
		text = aValue;
		return this;
	}

	/**
	 * Sets the value of the timestamp attribute.
	 */
	public CommentBuilder timestamp(long aValue){
		timestamp = aValue;
		return this;
	}

	/**
	 * Sets the value of the wishesUpdates attribute.
	 */
	public CommentBuilder wishesUpdates(boolean aValue){
		wishesUpdates = aValue;
		return this;
	}


	public Comment build(){
		return CommentFactory.createComment(this);
	}
}
